OnlineEclub/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using OnlineEclub.Data;
using OnlineEclub.Models;

namespace OnlineEclub.Controllers
{
    public class GroupController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GroupController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Group
        public async Task<IActionResult> Index()
        {
            //var applicationDbContext = _context.Group.Include(@ => @.Category).Include(@ => @.Content);  //Removing until we learn more.
            var applicationDbContext = _context.Group;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Group/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Group
                //.Include(@ => @.Category)  //Removing until we learn more.
                //.Include(@ => @.Content)
                .FirstOrDefaultAsync(m => m.GroupID == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // GET: Group/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Category, "CategoryID", "CategoryID");
            ViewData["ContentID"] = new SelectList(_context.Content, "ContentID", "ContentID");
            return View();
        }

        // POST: Group/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupID,GroupTitle,CategoryID,ContentID,MemberMin,MemberLimit")] Group @group)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Category, "CategoryID", "CategoryID", @group.CategoryID);
            ViewData["ContentID"] = new SelectList(_context.Content, "ContentID", "ContentID", @group.ContentID);
            return View(@group);
        }

        // GET: Group/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Group.FindAsync(id);
            if (@group == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Category, "CategoryID", "CategoryID", @group.CategoryID);
            ViewData["ContentID"] = new SelectList(_context.Content, "ContentID", "ContentID", @group.ContentID);
            return View(@group);
        }

        // POST: Group/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GroupID,GroupTitle,CategoryID,ContentID,MemberMin,MemberLimit")] Group @group)
        {
            if (id != @group.GroupID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.GroupID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Category, "CategoryID", "CategoryID", @group.CategoryID);
            ViewData["ContentID"] = new SelectList(_context.Content, "ContentID", "ContentID", @group.ContentID);
            return View(@group);
        }

        // GET: Group/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Group
                //.Include(@ => @.Category)  //Removing until we learn more.
                //.Include(@ => @.Content)
                .FirstOrDefaultAsync(m => m.GroupID == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // POST: Group/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @group = await _context.Group.FindAsync(id);
            _context.Group.Remove(@group);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroupExists(int id)
        {
            return _context.Group.Any(e => e.GroupID == id);
        }
    }
}

OnlineEclub/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineEclub.Models;

namespace OnlineEclub.Controllers
{
    public class HomeController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;

        public HomeController(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            if (_signInManager.IsSignedIn(User))
            {
                return View("Dashboard");
            }
            else
            {
                return View();
            }
        }

        public IActionResult Dashboard()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnlineEclub/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

OnlineEclub/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineEclub/Views/Home/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<div class="row" style="margin-top: 20px;">
    <div class="col-xs-offset-2 col-xs-8 col-sm-offset-4 col-sm-4">
        <input class="form-control" type="text" placeholder="Search" style="text-align: center;" />
    </div>
</div>
<div class="row">
    <div class="col-xs-12" style="border-bottom: 1px solid black;">
        <h3>
            My Groups&nbsp;&nbsp;&nbsp;<a asp-controller="Group" asp-action="Create">
                <i class="far fa-plus-square" style="color: green;"></i>
            </a>
        </h3>
    </div>
</div>
<div class="row">
    <div class="col-xs-12" id="GroupList">
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var Groups = [];

        for (var i = 0; i < 10; i++) {
            var group = {};
            group.GroupID = i;
            group.GroupName = "Group Name" + i;
            group.CategoryID = i;
            group.ContentID = i;
            group.MemberMin = 0;
            group.MemberLimit = 20;

            Groups.push(group);
        }

        $(document).ready(function () {
            GroupListRender();
        });

        function GroupListRender() {
            var html = "";

            $.each(Groups, function (index, value) {
                html += "<div><h4>" + value.GroupName + "</h4></div>";
            });

            $("#GroupList").html(html);
        }
    </script>
}

OnlineEclub/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@section Styles {
    <link href="~/css/Index.css" rel="stylesheet" type="text/css" />
}

<h1 class="text-center" style="margin-bottom:50px;">OnlineEclub</h1>

<div class="row text-center" style="width:50%;margin:20px auto 10px auto;">
    <a class="btn btn-lg btn-primary" asp-area="Identity" asp-page="/Account/Login">Login</a>
</div>
<div class="row text-center" style="width:50%;margin:0 auto;">
    <p style="text-decoration:underline;">or</p>
</div>
<div class="row text-center" style="width:50%;margin:10px auto 20px auto;">
    <a class="btn btn-lg btn-primary" asp-area="Identity" asp-page="/Account/Register">Register</a>
</div>